all: carmen1.png carmen2.png carmen3.png hammy1.png hammy2.png hammy3.png sherlie1.png sherlie2.png sherlie3.png


carmen1.png:
	wget -O $@ http://stephenverhalleman.com/static/images/carmen1.png
carmen2.png:
	wget -O $@ http://stephenverhalleman.com/static/images/carmen1.png
carmen3.png:
	wget -O $@ http://stephenverhalleman.com/static/images/carmen3.png
hammy1.png:
	wget -O $@ http://stephenverhalleman.com/static/images/hammy1.png
hammy2.png:
	wget -O $@ http://stephenverhalleman.com/static/images/hammy2.png
hammy3.png:
	wget -O $@ http://stephenverhalleman.com/static/images/hammy3.png
sherlie1.png:
	# Someone forgot to add the 1? I'll add it I guess.
	wget -O $@ http://stephenverhalleman.com/static/images/sherlie.png
sherlie2.png:
	wget -O $@ http://stephenverhalleman.com/static/images/sherlie2.png
sherlie3.png:
	wget -O $@ http://stephenverhalleman.com/static/images/sherlie3.png
